# Generated by Django 3.2 on 2022-02-25 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20220224_1412'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
